version: '3.8'

services:
  web:
    image: php:apache
    container_name: bwapp-web
    restart: always
    volumes:
      - .:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: bwapp-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bwapp
      MYSQL_USER: bwapp_user
      MYSQL_PASSWORD: bwapp_pass
    ports:
      - "3306:3306"
